---
abstract: 'App to generate Cisco NetFlow from Linux netfilter'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Netfilter-NetFlow
requires:
  Config: 0
  Config::Any: 0.15
  Config::General: 0
  Daemon::Generic: 0
  Exporter: 0
  ExtUtils::MakeMaker: 0
  File::Slurp: 9999.06
  File::Spec: 0
  Getopt::Long: 0
  IPC::Run: 0
  Log::Dispatch::Config: 0
  Log::Dispatch::Configurator::Any: 0
  POSIX: 0
  Time::HiRes: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Net-Netfilter-NetFlow
  homepage: https://github.com/ollyg/Net-Netfilter-NetFlow/wiki
  repository: git://github.com/ollyg/Net-Netfilter-NetFlow.git
version: 1.113260
